### ISSUE TITLE
CC examples for controlling tablet

### ISSUE THREAD

**Issue by 1tylermitchell** [ds84182/CCLights2#12]
Hi - hunting around for some examples and I haven't been able to find any.  Is there an example to program a tablet (I think I've got connecting with transceiver ok) that you can point me to?

**Comment by alekso56** [comment]
Well, right now the transceiver acts like a monitor that syncs with the connected tablet. 

So you place the transceiver beside/ontop/below the gpu and then use it like you would use a monitor. (after you connected the tablet by rightclicking)

i know, it doesn't make that much sense, but it'll propably be changed sooner or later.

if you understand the methods in the wiki, http://computercraft.info/wiki/CCLights2
then it should be fairly easy to program it.  example:

gpu = peripheral.wrap("left")
gpu.setColor(255,0,0) -- red
gpu.plot(0,0)  -- set pixel 0,0 to currentcolor
gpu.flipTextureV() -- flip texture vertically, moving the plotted pixel to 0,minheight
and so on.
