### ISSUE TITLE
Line 61 is bad and you should feel bad

### ISSUE THREAD

**Issue by ArcanoxDragon** [ds84182/CCLights2#14]
Line in question: 
https://github.com/ds84182/CCLights2/blob/d328ceec04bcd35a8645a38bdd6e27f424809a86/src/ds/mods/CCLights2/client/gui/GuiTablet.java#L61

alekso told me to complain about it D: recursion at 60fps is bad D:

**Comment by alekso56** [comment]
Dropping the blame on me?!
