### ISSUE TITLE
Caught Exception keeps server from launching.

### ISSUE THREAD

**Issue by circuitbomb** [ds84182/CCLights2#4]
MCPC+ 1.5.2
Forge 7.8.1.738
CC 1.53

CCLights2 "version" : "0.2"

http://pastebin.com/WtniZaLE

Seems fine single player.

**Comment by ds84182** [comment]
Oh, my bad, I forgot to use the @Side annotation. I'll fix this in a second.

**Comment by ds84182** [comment]
... Ok, at first I thought it was a bug with my source, but the problem is that I don't support the usage of MCPC+ with my mod. Any incompatibilities with it are a result of MCPC+'s derpyness, not my code, as I tested it in multiplayer.

**Comment by circuitbomb** [comment]
Seems setting -noverify at server launch works around any issue, no errors are being produced.

e.g. 

java -noverify -jar server.jar nogui

**Comment by Keridos** [comment]
this happens with a normal forge server too, forge 737 for MC 1.5.2 CC1.53

this line seems to cause the issue: this.setCreativeTab(ClientProxy.ccltab); in the blockGPU.java.
Maybe calling that on the server causes the exception?
